Gemfile

Add initial gems
initial settings for development

Add initial gems

---

Gemfile
Gemfile.lock
config/unicorn.rb

install & set unicorn
construct application server

unicorn install&settings

---

config/database.yml

create DB on EC2

---

config/routes.rb

modify routing users&items
for make ease to check views

modify routing users&items

---

.gitignore
Capfile
Gemfile
Gemfile.lock
config/deploy.rb
config/deploy/production.rb
config/deploy/staging.rb

auto deploy
make easy to deploy

auto deploy

---

.gitignore
app/controllers/items_controller.rb
app/models/evaluate.rb
app/models/first_genre.rb
app/models/item.rb
app/models/second_genre.rb
app/models/selling.rb
app/models/sold.rb
app/models/third_genre.rb
app/uploaders/image_uploader.rb
app/views/items/new.html.haml
app/views/layouts/application.html.erb
db/migrate/20190612062809_remove_buyer_id_from_items.rb
db/migrate/20190612062929_add_buyer_id_to_items.rb
db/migrate/20190612072156_add_brand_to_items.rb
db/schema.rb

items controller "new" "create"
sell items

Serverside item#new

---

Gemfile.lock
app/assets/javascripts/item_new.js
app/assets/stylesheets/application.scss
app/assets/stylesheets/items/buy.scss
app/assets/stylesheets/items/new.scss
app/views/items/buy.html.haml
app/views/items/new.html.haml
config/routes.rb
db/schema.rb

markup items#new
basic function

markup items#new

---

app/assets/javascripts/application.js

modify error on application.js
we can't use jQuery-ujs and rails-ujs at the same time

modify error

---

config/environments/production.rb

resolve error by modify code "config comment out"
resolve error

comment out config

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/stylesheets/application.scss
app/views/items/new.html.haml
app/views/layouts/application.html.haml

add gem dropzone

---

app/controllers/application_controller.rb
config/deploy.rb

basic authenticate
improve security

basic authenticate

---

app/assets/stylesheets/items/new.scss
app/views/items/new.html.haml
app/views/layouts/application.html.haml

modify errors by Dropzone for initial settings for S3
deploy production environment with using S3

modify errors by Dropzone

---

config/deploy.rb

modify deploy.rb BASIC_AUTH_PASSWORD
implement basic authenticate

modify deploy.rb BASIC_AUTH_PASSWORD

---

app/assets/javascripts/item_new.js
app/assets/stylesheets/items/new.scss
app/views/items/new.html.haml

item#new-size-brand
improve UX

item#new-size-brand

---

app/assets/javascripts/item_new.js

modify detail

---

app/assets/javascripts/application.js
app/assets/javascripts/delete.js
app/assets/javascripts/item_new.js
app/assets/stylesheets/items/new.scss
app/assets/stylesheets/users/mypage.scss
app/controllers/items_controller.rb
app/models/category.rb
app/models/item.rb
app/views/items/before_edit.html.haml
app/views/items/index.html.haml
app/views/items/new.html.haml
app/views/items/show.html.haml
app/views/users/_items_status.html.haml
app/views/users/_sidebar.html.haml
app/views/users/items_status.html.haml
db/schema.rb

ドロップゾーンの実装と削除機能

---

app/uploaders/image_uploader.rb
config/initializers/carrierwave.rb

S3 settings
use S3 in production

apply "fog"&"carrierwave"

---

app/assets/stylesheets/items/done.scss
app/views/items/done.html.haml

modify item#done view
improve ux

modify item#done view

---

config/deploy.rb
db/schema.rb

modify errors "pending migrate"&"ArgumentError: Missing required arguments: aws_secret_access_key"
resolve errors

modify errors

---

config/initializers/carrierwave.rb

modify code
resolve error
"uninitialized constant CarrierWave::Storage::Fog"

modify code for resolve error

---

app/assets/javascripts/breadcrumbs.js
app/assets/javascripts/header.js
app/assets/stylesheets/_header.scss
app/assets/stylesheets/items/_footer.scss
app/assets/stylesheets/items/index.scss
app/views/items/index.html.haml
app/views/users/edit.html.haml
app/views/users/info.html.haml
config/breadcrumbs.rb
config/initializers/carrierwave.rb

carrierwave.rbにendを追記。
トップページのjQuery修正。
ローカルサーバーを立ち上げる際にエラーが発生した為。

update carrierwave.rb add end

---

app/uploaders/image_uploader.rb
config/initializers/carrierwave.rb

modify settings for S3

---

app/assets/stylesheets/items/index.scss
app/assets/stylesheets/items/show.scss
app/controllers/items_controller.rb
app/views/items/buy.html.haml
app/views/items/done.html.haml
app/views/items/index.html.haml
app/views/items/show.html.haml
db/migrate/20190629065237_items_column_edit.rb
db/schema.rb

itemstatusの追加

---

app/assets/javascripts/item_new.js
app/assets/javascripts/jquery.validate.js
app/assets/javascripts/messages_ja.js
app/assets/stylesheets/items/new.scss
app/views/items/new.html.haml
app/views/layouts/application.html.haml

what
jQuery Validation(jquery.validate.min.js)のプラグインを用いた商品出品ページのバリデーションの実装。

商品出品のバリデーション

---

config/database.yml

resolve error "production DB"
use servise

utf8=> utf8mb4
